#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 599x447+767+388
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3196 1173
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Git Review"
    vTcl:DefineAlias "$top" "DiffToDoc" vTcl:Toplevel:WidgetProc "" 1
    text $top.tex39 \
        -background white -font TkTextFont -foreground black -height 154 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -undo 1 -width 574 -wrap word 
    .top37.tex39 configure -font TkTextFont
    .top37.tex39 insert end text
    vTcl:DefineAlias "$top.tex39" "txtCommitIds" vTcl:WidgetProc "DiffToDoc" 1
    text $top.tex40 \
        -background white -font TkTextFont -foreground black -height 164 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -undo 1 -width 574 -wrap word 
    .top37.tex40 configure -font TkTextFont
    .top37.tex40 insert end text
    vTcl:DefineAlias "$top.tex40" "txtFilters" vTcl:WidgetProc "DiffToDoc" 1
    entry $top.ent41 \
        -background white -disabledforeground {#a3a3a3} -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent41" "edName" vTcl:WidgetProc "DiffToDoc" 1
    label $top.lab42 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text Name: 
    vTcl:DefineAlias "$top.lab42" "Label1" vTcl:WidgetProc "DiffToDoc" 1
    label $top.lab43 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Commit IDs} 
    vTcl:DefineAlias "$top.lab43" "Label2" vTcl:WidgetProc "DiffToDoc" 1
    label $top.lab44 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text Exclude 
    vTcl:DefineAlias "$top.lab44" "Label3" vTcl:WidgetProc "DiffToDoc" 1
    button $top.but45 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command generateDiffDocument \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Generate 
    vTcl:DefineAlias "$top.but45" "Button1" vTcl:WidgetProc "DiffToDoc" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tex39 \
        -in $top -x 10 -y 30 -width 574 -relwidth 0 -height 154 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex40 \
        -in $top -x 10 -y 220 -width 574 -relwidth 0 -height 164 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent41 \
        -in $top -x 70 -y 400 -anchor nw -bordermode ignore 
    place $top.lab42 \
        -in $top -x 10 -y 400 -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 10 -y 0 -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 10 -y 190 -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 490 -y 400 -width 88 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

