#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Sep 06, 2017 12:03:19 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import gitreview_ui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Git_Review (root)
    gitreview_ui_support.init(root, top)
    root.mainloop()

w = None
def create_Git_Review(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Git_Review (w)
    gitreview_ui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Git_Review():
    global w
    w.destroy()
    w = None


class Git_Review:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'

        top.geometry("599x447+767+388")
        top.title("Git Review")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.txtCommitIds = Text(top)
        self.txtCommitIds.place(relx=0.02, rely=0.07, relheight=0.34
                , relwidth=0.96)
        self.txtCommitIds.configure(background="white")
        self.txtCommitIds.configure(font="TkTextFont")
        self.txtCommitIds.configure(foreground="black")
        self.txtCommitIds.configure(highlightbackground="#d9d9d9")
        self.txtCommitIds.configure(highlightcolor="black")
        self.txtCommitIds.configure(insertbackground="black")
        self.txtCommitIds.configure(selectbackground="#c4c4c4")
        self.txtCommitIds.configure(selectforeground="black")
        self.txtCommitIds.configure(undo="1")
        self.txtCommitIds.configure(width=574)
        self.txtCommitIds.configure(wrap=WORD)

        self.txtFilters = Text(top)
        self.txtFilters.place(relx=0.02, rely=0.49, relheight=0.37
                , relwidth=0.96)
        self.txtFilters.configure(background="white")
        self.txtFilters.configure(font="TkTextFont")
        self.txtFilters.configure(foreground="black")
        self.txtFilters.configure(highlightbackground="#d9d9d9")
        self.txtFilters.configure(highlightcolor="black")
        self.txtFilters.configure(insertbackground="black")
        self.txtFilters.configure(selectbackground="#c4c4c4")
        self.txtFilters.configure(selectforeground="black")
        self.txtFilters.configure(undo="1")
        self.txtFilters.configure(width=574)
        self.txtFilters.configure(wrap=WORD)

        self.edName = Entry(top)
        self.edName.place(relx=0.12, rely=0.89, relheight=0.04, relwidth=0.21)
        self.edName.configure(background="white")
        self.edName.configure(disabledforeground="#a3a3a3")
        self.edName.configure(foreground="#000000")
        self.edName.configure(highlightbackground="#d9d9d9")
        self.edName.configure(highlightcolor="black")
        self.edName.configure(insertbackground="black")
        self.edName.configure(selectbackground="#c4c4c4")
        self.edName.configure(selectforeground="black")

        self.Label1 = Label(top)
        self.Label1.place(relx=0.02, rely=0.89, height=21, width=41)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Name:''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.02, rely=0.0, height=21, width=69)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Commit IDs''')

        self.Label3 = Label(top)
        self.Label3.place(relx=0.02, rely=0.43, height=21, width=46)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Exclude''')

        self.Button1 = Button(top)
        self.Button1.place(relx=0.82, rely=0.89, height=24, width=88)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=gitreview_ui_support.generateDiffDocument)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Generate''')






if __name__ == '__main__':
    vp_start_gui()



