#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Sep 29, 2018 06:18:58 PM CEST  platform: Linux

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def addBranchDiffFromCommonAncestor(p1):
    print('mainwin_ui_support.addBranchDiffFromCommonAncestor')
    print('p1 = {0}'.format(p1))
    sys.stdout.flush()

def displayDiffPreview(p1):
    print('mainwin_ui_support.displayDiffPreview')
    print('p1 = {0}'.format(p1))
    sys.stdout.flush()

def generateDiffDocument(p1):
    print('mainwin_ui_support.generateDiffDocument')
    print('p1 = {0}'.format(p1))
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import mainwin_ui
    mainwin_ui.vp_start_gui()


