#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Sep 28, 2018 07:52:12 PM CEST  platform: Linux

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import textreport_ui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Report (root)
    textreport_ui_support.init(root, top)
    root.mainloop()

w = None
def create_Report(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Report (w)
    textreport_ui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Report():
    global w
    w.destroy()
    w = None


class Report:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("748x731+650+150")
        top.title("Report")
        top.configure(highlightcolor="black")



        self.txtReport = Text(top)
        self.txtReport.place(relx=0.027, rely=0.027, relheight=0.908
                , relwidth=0.944)
        self.txtReport.configure(background="white")
        self.txtReport.configure(font="TkTextFont")
        self.txtReport.configure(selectbackground="#c4c4c4")
        self.txtReport.configure(width=706)
        self.txtReport.configure(wrap=WORD)

        self.btOk = ttk.Button(top)
        self.btOk.place(relx=0.441, rely=0.944, height=28, width=92)
        self.btOk.configure(command=textreport_ui_support.closeWindow)
        self.btOk.configure(takefocus="")
        self.btOk.configure(text='''Ok''')






if __name__ == '__main__':
    vp_start_gui()



